# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \ 
    sed -i "s/ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/run/httpd/ /var/log/httpd/ && \
    chmod -R g=u /var/run/httpd/ /var/log/httpd/

ONBUILD COPY test.txt /tmp/

USER 1001

EXPOSE 8080
